# JPA
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
# servlet
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# Jackson
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=true
## HikariCP settings
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leakDetectionThreshold=2000
## Logging settings
logging.config=classpath:logback_config/logback.xml
logging.level.com.zaxxer.hikari=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari.HikariDataSource=DEBUG
