# spring.application.name=spring-server

# # Server Identity Keys (base64 PEM)
# SERVER_IDENTITY_PRIV_B64=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1V6UnFFVnV4QWI3VVJhZ3IKWG1kVzlqTi80aEUyQUZkaWpSc3AxMVhsc3l1aFJBTkNBQVN5L2lNMGlxYmduQnlBZVpPU29WaER3c09BZlJUbQo3OWliQ3F4QXVkRXl3UVVKUFFmYVZtT3FoSXZlWWw5Q0JjaUhTWG02ZmdJZmVuU1VVWk5JMjI0WQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
# SERVER_IDENTITY_PUB_B64=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFc3Y0ak5JcW00SndjZ0htVGtxRllROExEZ0gwVQo1dS9ZbXdxc1FMblJNc0VGQ1QwSDJsWmpxb1NMM21KZlFnWEloMGw1dW40Q0gzcDBsRkdUU050dUdBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
