package org.web.common.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum City {
    AN_GIANG("Tỉnh An Giang"),
    BA_RIA_VUNG_TAU("Tỉnh Bà Rịa - Vũng Tàu"),
    BAC_GIANG("Tỉnh Bắc Giang"),
    BAC_KAN("Tỉnh Bắc Kạn"),
    BAC_LIEU("Tỉnh Bạc Liêu"),
    BAC_NINH("Tỉnh Bắc Ninh"),
    BEN_TRE("Tỉnh Bến Tre"),
    BINH_DINH("Tỉnh Bình Định"),
    BINH_DUONG("Tỉnh Bình Dương"),
    BINH_PHUOC("Tỉnh Bình Phước"),
    BINH_THUAN("Tỉnh Bình Thuận"),
    CA_MAU("Tỉnh Cà Mau"),
    CAO_BANG("Tỉnh Cao Bằng"),
    CAN_THO("Thành phố Cần Thơ"),
    DA_NANG("Thành phố Đà Nẵng"),
    DAK_LAK("Tỉnh Đắk Lắk"),
    DAK_NONG("Tỉnh Đắk Nông"),
    DIEN_BIEN("Tỉnh Điện Biên"),
    DONG_NAI("Tỉnh Đồng Nai"),
    DONG_THAP("Tỉnh Đồng Tháp"),
    GIA_LAI("Tỉnh Gia Lai"),
    HA_GIANG("Tỉnh Hà Giang"),
    HA_NAM("Tỉnh Hà Nam"),
    HA_NOI("Thành phố Hà Nội"),
    HA_TINH("Tỉnh Hà Tĩnh"),
    HAI_DUONG("Tỉnh Hải Dương"),
    HAI_PHONG("Thành phố Hải Phòng"),
    HAU_GIANG("Tỉnh Hậu Giang"),
    HOA_BINH("Tỉnh Hòa Bình"),
    HO_CHI_MINH("Thành phố Hồ Chí Minh"),
    HUE("Thành phố Huế"),
    HUNG_YEN("Tỉnh Hưng Yên"),
    KHANH_HOA("Tỉnh Khánh Hòa"),
    KIEN_GIANG("Tỉnh Kiên Giang"),
    KON_TUM("Tỉnh Kon Tum"),
    LAI_CHAU("Tỉnh Lai Châu"),
    LAM_DONG("Tỉnh Lâm Đồng"),
    LANG_SON("Tỉnh Lạng Sơn"),
    LAO_CAI("Tỉnh Lào Cai"),
    LONG_AN("Tỉnh Long An"),
    NAM_DINH("Tỉnh Nam Định"),
    NGHE_AN("Tỉnh Nghệ An"),
    NINH_BINH("Tỉnh Ninh Bình"),
    NINH_THUAN("Tỉnh Ninh Thuận"),
    PHU_THO("Tỉnh Phú Thọ"),
    PHU_YEN("Tỉnh Phú Yên"),
    QUANG_BINH("Tỉnh Quảng Bình"),
    QUANG_NAM("Tỉnh Quảng Nam"),
    QUANG_NGAI("Tỉnh Quảng Ngãi"),
    QUANG_NINH("Tỉnh Quảng Ninh"),
    QUANG_TRI("Tỉnh Quảng Trị"),
    SOC_TRANG("Tỉnh Sóc Trăng"),
    SON_LA("Tỉnh Sơn La"),
    TAY_NINH("Tỉnh Tây Ninh"),
    THAI_BINH("Tỉnh Thái Bình"),
    THAI_NGUYEN("Tỉnh Thái Nguyên"),
    THANH_HOA("Tỉnh Thanh Hóa"),
    TIEN_GIANG("Tỉnh Tiền Giang"),
    TRA_VINH("Tỉnh Trà Vinh"),
    TUYEN_QUANG("Tỉnh Tuyên Quang"),
    THU_DUC("Thành phố Thủ Đức"),
    VINH_LONG("Tỉnh Vĩnh Long"),
    VINH_PHUC("Tỉnh Vĩnh Phúc"),
    YEN_BAI("Tỉnh Yên Bái");

    private final String displayName;
}
