server:
  port: 8082
  tomcat:
    relaxed-query-chars: "|,{,},[,]"
  # CORS Configuration
  cors:
    allowed-origins: http://localhost:8000,http://127.0.0.1:8000
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    exposed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
    allow-credentials: true
    max-age: 3600

app:
  module:
    email:
      enabled: true
      config:
        debug: false
spring:
  application:
    name: cms-service
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: none
              create-target: migration/sql/init_ddl.sql
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    validate-on-migrate: true

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  data:
    redis:
      host: 42.117.1.83
      password: xBase!@#456
      ssl:
        enabled: false
      port: 16379
      database: 10

database:
  writer:
    url: jdbc:mysql://localhost:33003/cms_dev?useSSL=false
    username: cms_dev
    password: "cms_dev!@#456"
  reader:
    url: jdbc:mysql://localhost:33003/cms_dev?useSSL=false
    username: cms_dev
    password: "cms_dev!@#456"

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
  jwtRefreshExpirationS: 86400
  jwtAccessTokenExpirationS: 300

springdoc:
  # Specify the path of the OpenAPI documentation
  api-docs.path: /api-docs
  swagger-ui:
    # Specify the path of the Swagger UI
    path: /swagger-ui.html
    # Enable or disable Swagger UI
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.*: INFO
    dev.xbase.*: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE