version: '3'
services:
  xbase-cms-ui:
    image: vunt/xbase_cms_ui:__DOCKER_TAG__
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 20m
    networks:
      - pronet
    environment:
      ENV_BACKEND_HOST: "http://xbase-cms-backend:8082"

networks:
  pronet:
    external:
      name: pronet
