erDiagram
    USERS {
        bigint id PK
        varchar email UK
        varchar kyc_status
        varchar trust_level
    }

    USER_IDENTITIES {
        bigint id PK
        bigint user_id FK
        varchar document_type
        varchar identity_number UK
        varchar full_name
        date date_of_birth
        varchar gender
        varchar nationality
        varchar place_of_residence
        varchar identity_verification_status
        boolean ocr_extracted
        boolean manual_verified
        datetime verified_at
    }

    VERIFICATION_SESSIONS {
        bigint id PK
        bigint user_id FK
        varchar status
        varchar verification_type
        datetime started_at
        datetime submitted_at
        datetime completed_at
        varchar failure_reason
        varchar review_note
    }

    VERIFICATION_ARTIFACTS {
        bigint id PK
        bigint verification_session_id FK
        varchar artifact_type
        varchar artifact_status
        varchar storage_key
        varchar mime_type
        bigint file_size
        varchar checksum
        datetime uploaded_at
    }

    VERIFICATION_RESULTS {
        bigint id PK
        bigint verification_session_id FK
        varchar ocr_provider
        double ocr_confidence
        varchar decision_source
        boolean document_valid
        boolean document_tampered
        varchar extracted_full_name
        varchar extracted_identity_number
        text raw_ocr_json
        datetime processed_at
    }

    FACE_VERIFICATION_RESULTS {
        bigint id PK
        bigint verification_session_id FK
        double face_match_score
        boolean face_match_passed
        double liveness_score
        boolean liveness_passed
        boolean spoof_detected
        double face_quality_score
        datetime processed_at
    }

    RISK_ASSESSMENTS {
        bigint id PK
        bigint verification_session_id FK
        double risk_score
        varchar risk_level
        boolean ip_risk_flag
        boolean blacklist_hit
        boolean manual_review_required
        varchar reason
    }

    VERIFICATION_REVIEWS {
        bigint id PK
        bigint verification_session_id FK
        bigint reviewer_id
        varchar review_action
        varchar note
        datetime reviewed_at
    }

    USERS ||--o| USER_IDENTITIES : "có danh tính"
    USERS ||--o{ VERIFICATION_SESSIONS : "khởi tạo"

    VERIFICATION_SESSIONS ||--o{ VERIFICATION_ARTIFACTS : "chứa tệp"
    VERIFICATION_SESSIONS ||--o| VERIFICATION_RESULTS : "có OCR"
    VERIFICATION_SESSIONS ||--o| FACE_VERIFICATION_RESULTS : "có Face Match"
    VERIFICATION_SESSIONS ||--o| RISK_ASSESSMENTS : "được đánh giá"
    VERIFICATION_SESSIONS ||--o{ VERIFICATION_REVIEWS : "được xét duyệt"