server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /pub {
    proxy_pass <ENV_BACKEND_HOST>;
  }
  location /api {
    proxy_pass <ENV_BACKEND_HOST>/api;
    rewrite /api/(.*)$ /$1 break;
  }

  location / {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";
    try_files $uri $uri/ /index.html;
  }
}
